### ISSUE TITLE
Throwing errors with the latest version of the automatic webui

### ISSUE THREAD

**Issue by eware-godaddy** [amotile/stable-diffusion-workshop#1]
Thanks for building this tool. It's very exciting, and I'm looking forward to this amazing workflow.

I'm having an issue running this against the latest code in the automatic webui.

I've got the latest commit of the automatic webui installed https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/5a1951f17567022612aef5302fb650923a06fb54

There appears to be an additional parameter being passed through which is causing gradio to throw an error.

I get the following errors from the webui:

```
TypeError: string indices must be integers
Traceback (most recent call last):
  File "/home/eware/anaconda3/envs/sd-automatic/lib/python3.9/site-packages/gradio/routes.py", line 273, in run_predict
    output = await app.blocks.process_api(
  File "/home/eware/anaconda3/envs/sd-automatic/lib/python3.9/site-packages/gradio/blocks.py", line 750, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/eware/anaconda3/envs/sd-automatic/lib/python3.9/site-packages/gradio/blocks.py", line 615, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
IndexError: list index out of range
```
Here's an example of a web request from the latest webui with 36 elements in it:

``` json
{
  "fn_index": 10,
  "data": [
    "an orange cat smoking a cigar, fat cat, business man, concept art, 4k",
    "",
    "None",
    "None",
    20,
    "Euler a",
    false,
    false,
    1,
    1,
    7,
    -1,
    -1,
    0,
    0,
    0,
    false,
    512,
    512,
    false,
    false,
    0.7,
    "None",
    "",
    false,
    null,
    "",
    false,
    "Seed",
    "",
    "Steps",
    "",
    true,
    null,
    "{\"prompt\": \"an orange cat smoking a cigar, fat cat, business man, concept art, 4k\", \"all_prompts\": [\"an orange cat smoking a cigar, fat cat, business man, concept art, 4k\"], \"negative_prompt\": \"\", \"seed\": 486859185, \"all_seeds\": [486859185], \"subseed\": 400618458, \"all_subseeds\": [400618458], \"subseed_strength\": 0, \"width\": 512, \"height\": 512, \"sampler_index\": 0, \"sampler\": \"Euler a\", \"cfg_scale\": 7, \"steps\": 20, \"batch_size\": 1, \"restore_faces\": false, \"face_restoration_model\": null, \"sd_model_hash\": \"7460a6fa\", \"seed_resize_from_w\": 0, \"seed_resize_from_h\": 0, \"denoising_strength\": null, \"extra_generation_params\": {}, \"index_of_first_image\": 0}",
    "<p>an orange cat smoking a cigar, fat cat, business man, concept art, 4k<br>\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 486859185, Size: 512x512</p><div class='performance'><p class='time'>Time taken: <wbr>3.40s</p><p class='vram'>Torch active/reserved: 3161/3688 MiB, <wbr>Sys VRAM: 5393/24269 MiB (22.22%)</p></div>"
  ],
  "session_hash": "4umtmkku44w"
}
```

The payload from the workshop front-end is passing through 35 elements:

``` json
{
  "fn_index": 10,
  "data": [
    "an orange cat smoking a cigar, fat cat, business man, concept art, 4k",
    "",
    "None",
    "None",
    15,
    "LMS",
    false,
    false,
    1,
    1,
    7.5,
    "1468895597",
    -1,
    0,
    0,
    0,
    false,
    512,
    512,
    false,
    false,
    0.7,
    "None",
    false,
    null,
    "",
    false,
    "Seed",
    "",
    "Steps",
    "",
    true,
    null,
    "",
    ""
  ],
  "session_hash": "d1h1f518vfu"
}
```

**Comment by amotile** [comment]
I tested it against the very latest now and it seems to work (for now).

full git hash: e235d4e691e81cc3628da762b3f4ace936a44036

So you can try update your AUTOMATIC1111 version.

If you know how to run the project locally (It's just a normal Create-React-App) it's relatively easy to adjust this part.

The code for it is here:
https://github.com/amotile/stable-diffusion-workshop/blob/main/src/features/processing/backend_automatic1111.ts
